name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "npm ci"
      run: npm ci

    - name: "unit test"
      run: npm run test
    
    - name: "integration test"
      run: node ./lib/main.js
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
    
    - name: Readable Readme
      uses: tianhaoz95/readable-readme@v0.1.2-alpha
      with:
        token: ${{ secrets.TEST_GITHUB_TOKEN }}

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                 "and check in all changes" \
            && exit 1)
